logging:
  level:
    org:
      hibernate:
        nodeValue: ERROR
        SQL: DEBUG
      springframework:
        web: DEBUG
#spring:
#  datasource:
#    username: root
#    url: jdbc:mysql://localhost:3306/docker_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
#    password: root
#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: 'true'

